version: '3'

services:
  app:
    build: .
    container_name: flask_app
    restart: always
    networks:
      - net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - net

networks:
  net:
    driver: bridge